monolog:
    use_microseconds: false
    handlers:
        #main:
        #    type: stream
        #    path: "%kernel.logs_dir%/%kernel.environment%.log"
        #    level: debug
        #    channels: ["!event", "!app"]

        #console:
        #    type: console
        #    process_psr_3_messages: false
        #    channels: ["!event", "!doctrine", "!console"]

        app:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.app.log"
            level: info
            channels: ["app"]